services:
  backend:
    build: /backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - intelliparse

  frontend:
    build: /frontend
    container_name: frontend
    ports:
      - "5173:5173"
    command: npm run dev
    env_file:
      - ./frontend/.env
    networks:
      - intelliparse

networks:
  intelliparse:
    driver: bridge
